export const modelConfigs = [
    {
      name: "room",   // Modelin ismi
      type: "room",        // Modelin türü
      path: "room.glb", // Dosya yolu
      position: [0,0,0],
      scale: [1,1,1],
      rotation: [0, 0, 0],
    },
    {
      name: "sofa_1",   // Modelin ismi
      type: "sofa",        // Modelin türü
      path: "./models/sofa/sofa_1.glb", // Dosya yolu
      position: [-2.5, 0, 2],
      scale: [0.013, 0.013, 0.013],
      rotation: [0, Math.PI, 0],
    },
    {
      name: "sofa_2",
      type: "sofa",
      path: "./models/sofa/sofa_2.glb",
      position: [-2.5, 0, 2],
      scale: [1,1,1],
      rotation: [0, Math.PI / 2, 0],
    },
    {
      name: "sofa_3",
      type: "sofa",
      path: "./models/sofa/sofa_3.glb",
      position: [-2.5, 0, 2],
      scale: [0.04, 0.04, 0.04],
      rotation: [0, Math.PI, 0],
    },
    {
      name: "sofa_4",
      type: "sofa",
      path: "./models/sofa/sofa_4.glb",
      position: [-4.4, 0, 2],
      scale: [0.018, 0.018, 0.018],
      rotation: [0, Math.PI/2, 0],
    },
    {
      name: "sofa_5",
      type: "sofa",
      path: "./models/sofa/sofa_5.glb",
      position: [-2.5, 0, 2],
      scale: [0.015, 0.015, 0.015],
      rotation: [0, Math.PI/2, 0],
    },
    {
      name: "armchair",
      type: "armchair",
      path: "./models/armchair/armchair.glb",
      position: [-2.5, 0, -1],
      scale: [0.02, 0.02, 0.02],
      rotation: [0, -Math.PI / 2, 0],
    },
    {
      name: "armchair_2",
      type: "armchair",
      path: "./models/armchair/armchair_2.glb",
      position: [-2.4, 0, -1],
      scale: [2, 2, 2],
      rotation: [0, Math.PI / 2, 0],
    },
    {
      name: "armchair_3",
      type: "armchair",
      path: "./models/armchair/armchair_3.glb",
      position: [-2.4, 0, -1],
      scale: [2.2, 2.2, 2.2],
      rotation: [0, Math.PI / 2, 0],
    },
    {
      name: "carpet",
      type: "carpet",
      path: "./models/carpet/carpet.glb",
      position: [0, 0, 0],
      scale: [0.8, 0.8, 0.8],
      rotation: [0, Math.PI / 2, 0],
    },
    {
      name: "carpet_2",
      type: "carpet",
      path: "./models/carpet/carpet_2.glb",
      position: [1, 0, -0.2],
      scale: [1.5, 1.5, 1.5],
      rotation: [0, -Math.PI/2 , 0],
    },
    {
      name: "carpet_3",
      type: "carpet",
      path: "./models/carpet/carpet_3.glb",
      position: [0.1, 0, 0.2],
      scale: [0.03, 0.03, 0.04],
      rotation: [0, 0, 0],
    },
    {
      name: "carpet_4",
      type: "carpet",
      path: "./models/carpet/carpet_4.glb",
      position: [-1, 0, 0.1],
      scale: [1.5, 1.5, 1.5],
      rotation: [0, Math.PI/2, 0],
    },
    {
      name: "carpet_5",
      type: "carpet",
      path: "./models/carpet/carpet_5.glb",
      position: [0.1, 0, 0],
      scale: [1.25, 1.25, 1.25],
      rotation: [0, 0, 0],
    },
    {
      name: "bookshelf",
      type: "bookshelf",
      path: "./models/bookshelf/bookshelf.glb",
      position: [3, 0, -13],
      scale: [2, 2, 2],
      rotation: [0, -Math.PI / 2, 0],
    },
    {
      name: "bookshelf_2",
      type: "bookshelf",
      path: "./models/bookshelf/bookshelf_2.glb",
      position: [4, 2.4, 5],
      scale: [2, 2, 2],
      rotation: [0, -Math.PI / 2, 0],
    },
    {
      name: "bookshelf_3",
      type: "bookshelf",
      path: "./models/bookshelf/bookshelf_3.glb",
      position: [2, 0, 4.6],
      scale: [1.6, 1.6, 1.6],
      rotation: [0, -Math.PI / 2, 0],
    },
    
    {
      name: "table",
      type: "table",
      path: "./models/table/table.glb",
      position: [0, 0, 0],
      scale: [0.6, 0.6, 0.6],
      rotation: [0, 0, 0],
    },
    {
      name: "table_2",
      type: "table",
      path: "./models/table/table_2.glb",
      position: [0, 0.35, 0],
      scale: [1, 1, 1],
      rotation: [0, Math.PI/2, 0],
    },
    {
      name: "table_3",
      type: "table",
      path: "./models/table/table_3.glb",
      position: [0, 0.35, 0],
      scale: [1.5, 1.5, 1.5],
      rotation: [0, 0, 0],
    },
    {
      name: "table_4",
      type: "table",
      path: "./models/table/table_4.glb",
      position: [-1, 0, 0.6],
      scale: [0.0015, 0.0015, 0.0015],
      rotation: [0, 0, 0],
    },
    {
      name: "table_5",
      type: "table",
      path: "./models/table/table_5.glb",
      position: [0, 0.35, 0],
      scale: [1, 1, 1],
      rotation: [0, Math.PI/2, 0],
    },
    
    
    {
      name: "tv",
      type: "tv",
      path: "./models/tv/tv_screen.glb",
      position: [3.2, 1.8, 0],
      scale: [0.035, 0.035, 0.035],
      rotation: [0, -Math.PI /2, 0],
    },
    {
      name: "decoration",
      type: "decoration",
      path: "./models/decoration/decoration.glb",
      position: [-1, 0, 4.8],
      scale: [4, 4, 4],
      rotation: [0, Math.PI /2, 0],
    },
    {
      name: "decoration_2",
      type: "decoration",
      path: "./models/decoration/decoration_2.glb",
      position: [0, 0.65, 3.7],
      scale: [0.10, 0.10, 0.10],
      rotation: [0, 0, 0],
    },
    {
      name: "decoration_3",
      type: "decoration",
      path: "./models/decoration/decoration_3.glb",
      position: [-1.5, 0, 4.8],
      scale: [1.1, 1.1, 1.1],
      rotation: [0, Math.PI/2, 0],
    },
    {
      name: "decoration_4",
      type: "decoration",
      path: "./models/decoration/decoration_4.glb",
      position: [-1.5, 0, 4.3],
      scale: [0.06, 0.06, 0.06],
      rotation: [0, 0, 0],
    },
    
    {
      name: "picture",
      type: "picture",
      path: "./models/wall_picture/wall_picture.glb",
      position: [-1, 2.4, 5],
      scale: [1, 1, 1],
      rotation: [0, Math.PI , 0],
    },
    {
      name: "picture_2",
      type: "picture",
      path: "./models/wall_picture/wall_picture_2.glb",
      position: [1.5, 1.5, 4.8],
      scale: [0.040, 0.040, 0.040],
      rotation: [0, Math.PI , 0],
    },
    {
      name: "picture_3",
      type: "picture",
      path: "./models/wall_picture/wall_picture_3.glb",
      position: [-1, 2.4, 5],
      scale: [0.25, 0.25, 0.25],
      rotation: [0, Math.PI , 0],
    },
    
    {
      name: "tv_table",
      type: "tv_table",
      path: "./models/tv_table/tv_table.glb",
      position: [3, 0.1, 0],
      scale: [1,1,1],
      rotation: [0, -Math.PI/2 , 0],
    },
    
    
    {
      name: "tv_table_2",
      type: "tv_table",
      path: "./models/tv_table/tv_table_2.glb",
      position: [3, 0, 0],
      scale: [1,1,1],
      rotation: [0, -Math.PI/2 , 0],
    },
    {
      name: "tv_table_3",
      type: "tv_table",
      path: "./models/tv_table/tv_table_3.glb",
      position: [2.6, 0, -0.75],
      scale: [0.8, 0.8, 0.8],
      rotation: [0, -Math.PI/2 , 0],
    },
    {
      name: "tv_table_4",
      type: "tv_table",
      path: "./models/tv_table/tv_table_4.glb",
      position: [0.1, 0, -5.30],
      scale: [0.008, 0.008, 0.008],
      rotation: [0, 0 , 0],
    },
    {
      name: "tv_table_5",
      type: "tv_table",
      path: "./models/tv_table/tv_table_5.glb",
      position: [3.9, 0, 0],
      scale: [1, 1, 1],
      rotation: [0, Math.PI/2, 0],
    },
    
  ];
  